### PR TITLE
packages: edit versioning fields for k8s-1.32 prerelease

### PR DESCRIPTION
**Pull request by koooosh**
**Issue number:**

Closes # N/a

**Description of changes:**

The boilerplates for `kubernetes-1.32` and `ecr-credential-provider-1.32` packages were added in #298 .

However, given these packages are still in prerelease, we are downgrading the `Release` field to < 1 in order to signal this (following [this guideline](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_prerelease_versions)).

Also following that guideline, we are updating the `Version` field to match the new prerelease version.

**Testing done:**

`make ARCH=aarch64 && make ARCH=x86_64`

```
[downgrade-k8s-1.32]$ rpm -qpi build/rpms/kubernetes-1.32/bottlerocket-kubelet-1.32-1.32.0-0.beta1.1733797561.23b442b1.br1.x86_64.rpm 
Name        : bottlerocket-kubelet-1.32
Epoch       : 1
Version     : 1.32.0
Release     : 0.beta1.1733797561.23b442b1.br1
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 1515309
License     : Apache-2.0 AND BSD-3-Clause
Signature   : (none)
Source RPM  : bottlerocket-kubernetes-1.32.0-0.beta1.1733797561.23b442b1.br1.src.rpm
Build Date  : Tue Dec 10 22:52:15 2024
Build Host  : localhost
URL         : https://github.com/kubernetes/kubernetes
Summary     : Container cluster node agent
Description :
Container cluster node agent.
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by koooosh** [comment]
^ Force push changes the Release from `0` to `0.beta1` for further flexibility

**Review by Sparksssj — APPROVED** [review]

**Review by ginglis13 — APPROVED** [review]

**Review by yeazelm — APPROVED** [review]
I see that the `beta1` is dropped from our `Release` field. I think this is fine for the purposes of this change (since it starts with a `0` which is the most important part), but if we are going to do more pre-release software like this in the future, we should make check to see if we need to change this behavior.

**Comment by koooosh** [comment]
Upon inspecting an updated rpm, looks like the `beta1` is stripped from the Release field. If we want to keep `beta1`, it looks like we may have to update twoliter as well

**Comment by koooosh** [comment]
So as a sanity check, I rebuilt the core-kit and this time, I do see the `beta1`:
```
[downgrade-k8s-1.32]$ rpm -qpi build/rpms/kubernetes-1.32/bottlerocket-kubelet-1.32-1.31.1-0.beta1.1733797561.23b442b1.br1.x86_64.rpm 
Name        : bottlerocket-kubelet-1.32
Epoch       : 1
Version     : 1.31.1
Release     : 0.beta1.1733797561.23b442b1.br1
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 1515309
License     : Apache-2.0 AND BSD-3-Clause
Signature   : (none)
Source RPM  : bottlerocket-kubernetes-1.31.1-0.beta1.1733797561.23b442b1.br1.src.rpm
Build Date  : Tue Dec 10 19:56:13 2024
Build Host  : localhost
URL         : https://github.com/kubernetes/kubernetes
Summary     : Container cluster node agent
Description :
Container cluster node agent.
```

I'll ask another engineer to verify this.

**Review by bcressey — DISMISSED** [review]

**Comment by Sparksssj** [comment]
Made verification and the result looks good.
```
$ rpm -qpi bottlerocket-kube-proxy-1.32-fips-bin-1.31.1-0.beta1.1733797561.23b442b1.br1.aarch64.rpm
Name        : bottlerocket-kube-proxy-1.32-fips-bin
Epoch       : 1
Version     : 1.31.1
Release     : 0.beta1.1733797561.23b442b1.br1
Architecture: aarch64
Install Date: (not installed)
Group       : Unspecified
Size        : 71680944
License     : Apache-2.0 AND BSD-3-Clause
Signature   : (none)
Source RPM  : bottlerocket-kubernetes-1.31.1-0.beta1.1733797561.23b442b1.br1.src.rpm
Build Date  : Tue 10 Dec 2024 09:06:38 PM UTC
Build Host  : localhost
URL         : https://github.com/kubernetes/kubernetes
Summary     : Container cluster node proxy binaries, FIPS edition
Description :
Container cluster node proxy binaries, FIPS edition.
```

**Comment by koooosh** [comment]
^ Force push also updates the `Version` field to prerelease version as suggested by guideline. Thanks @ginglis13 for the callout

**Review by ginglis13 — APPROVED** [review]

**Review by bcressey — CHANGES_REQUESTED** [review]
Please update the k8s 1.32 package to actually use k8s 1.32 sources.

**Comment by koooosh** [comment]
Cancelling this PR as we are reverting the boilerplate, see #312

**Pull request closed without merging**
