### PR TITLE
Sync 3.3.x branch with develop

### PR DESCRIPTION
**Pull request by ginglis13**
**Description of changes:**

Cherry pick the below commits (excluding merge commits and https://github.com/bottlerocket-os/bottlerocket-core-kit/commit/58b4f48a843cb4c3fa898589d8550a7880ec87fe, which hasn't released yet) from develop the `3.3.x` branch

```
git log --oneline upstream/develop 3.3.x

c866f93a (HEAD -> develop, upstream/develop) Merge pull request #265 from ginglis13/force-use-kernel-upstreams
dc9aff2d (tag: v3.3.2) Merge pull request #268 from piyush-jena/v3.3.2-prep
a64e24a6 twoliter: bump release version to 3.3.2
adce83fe changelog: add notes for 3.3.2 release
58b4f48a (origin/force-use-kernel-upstreams, force-use-kernel-upstreams) packages: use upstream amazon linux sources
87675830 Merge pull request #266 from yeazelm/fix_ipv6
0164c961 kernel-5.15: Add patch to fix IPv6 typo
b987230a (tag: v3.3.1) Merge pull request #264 from ginglis13/prepare-3.3.1
4684d964 Merge pull request #263 from cezar-r/kernels-2024-11-14
41ae9ae8 kernel-6.1: update to 6.1.115
ee8ed469 (origin/prepare-3.3.1, prepare-3.3.1) changelog: add notes for 3.3.1 release
f7a8503b twoliter: bump release version to 3.3.1
a149006a kernel-5.10: update to 5.10.228
a70fd814 (HEAD -> 3.3.x, upstream/3.3.x) Merge pull request #260 from ginglis13/nvidia-cve-backport-3.2.0
```

**Testing done:**

build core kit

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by ginglis13** [comment]
^ force push drops cherry-pick of 58b4f48a843cb4c3fa898589d8550a7880ec87fe which hasn't been released yet

**Review by yeazelm — APPROVED** [review]

**Comment by bcressey** [comment]
Why don't we just fast-forward the 3.3.x branch instead of doing all these cherry picks? Is there a specific commit we're trying not to release yet? If so, we could revert just that one after a fast-forward.

**Comment by ginglis13** [comment]
> Why don't we just fast-forward the 3.3.x branch instead of doing all these cherry picks? Is there a specific commit we're trying not to release yet? If so, we could revert just that one after a fast-forward.

@bcressey I don't have a good enough answer to that other than avoiding merge commits; there's no specific commit that's been merged to develop which we aren't prepared to release; I can adjust this PR to be a ff merge of develop -> 3.3.x

**Comment by ginglis13** [comment]
^ force push fastforward merges develop into 3.3.x via `git merge develop backport-3.3.x`

**Comment by ginglis13** [comment]
We haven't had any releases in the 3.3.x series that requires any backporting, cherry picking, etc. etc, so I'm closing this PR.

**Pull request closed without merging**
